export const FETCH_FRIEND = 'FETCH_FRIEND';
export const SET_FRIENDS = 'SET_FRIENDS';
export const FETCHFEED = 'FETCHFEED';
export const LOAD_MORE_FRIENDS = 'LOAD_MORE_FRIENDS';
export const TWEET_CHANGED = 'TWEET_CHANGED';
export const TWEET_CLEAR = 'TWEET_CLEAR';
